### ISSUE TITLE
GitHub CI pipeline is malformed

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#433]
## Current behavior

Thew GitHub CI template gets generated invalid:

```yml
name: CI

on:
  push:
    branches:
      - main
      - release/**

  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - release/**
env:
  STEP_TIMEOUT_MINUTES: 60

jobs:
  smoke_test:
    name: Smoke Test (Debug Build of UnoApp26)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        timeout-minutes: ${{ fromJSON(env.STEP_TIMEOUT_MINUTES) }}
        uses: "./.github/steps/install_dependencies"

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build UnoApp26 (Debug)
        shell: pwsh
        run: msbuild ./UnoApp26/UnoApp26.csproj /r
UnoApp26.Tests (Release)
        shell: pwsh
        run: msbuild ./UnoApp26.Tests/UnoApp26.Tests.csproj /p:Configuration=Release /p:OverrideTargetFrameworks=net8.0 /r

      - name: Run Unit Tests
        shell: pwsh
        run: dotnet test ./UnoApp26.Tests/UnoApp26.Tests.csproj --no-build -c Release --logger GitHubActions --blame-crash --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
#endif
```

Note that the whole section starting the incorrectly indented `UnoApp26.Tests` line should not be there as I did not include tests in the setup (see repro steps below).

## Expected behavior

Should be valid YAML

## How to reproduce it (as minimally and precisely as possible)

I used the Blank template with .NET 8, all target platforms and GitHub pipeline as CI option. After creation, the `ci.yml` file was malformed. I tried two times with the same result.
