### ISSUE TITLE
Add XamlStyler as option for ci pipeline

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.templates#460]
## What would you like to be added:

Run XamlStyler as a job in the ci pipeline that gets created from template (xaml markup only)
```yml
name: Xaml Styler

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  xaml-styler:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Install XAML Styler 
      run: dotnet tool update --global XamlStyler.Console
    - name: Verify XAML Styling
      run: xstyler -r -l Verbose -c src/Settings.XamlStyler -d "." --passive
```
## Why is this needed:

Helps ensure a standard xaml layout
